# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS (required for v2)
build:
  os: ubuntu-22.04

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Use conda environment (Python version specified in docs_env.yaml)
conda:
  environment: docs_env.yaml

# Build PDF & ePub
formats:
  - pdf