# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS and tools (required for v2)
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Use conda to install dependencies
python:
  install:
    - method: conda
      path: docs_env.yaml

# Build PDF & ePub
formats:
  - pdf