name: mbarq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - mageck
  - python>=3.8
  - blast==2.9.*
  - bedtools==2.30.*
  - biopython==1.79
  - numpy=1.22
  - pandas
  - pytest
  - click
  - pip
  - pandera
  - pyranges==0.0.117
  - pybedtools == 0.9.0

