root: manuscript_data
figures_dir: figures


nguyen:
    map_file: library_11_1_l50.annotated.csv.gz
    counts_file: library_11_1_mbarq_merged_counts.csv.gz 
    results_file: library_11_1_rra_results.csv.gz 
    sample_data_file: nguyen_2020_sample_data.csv.gz
    published_results_file: nguyen_2020_published_results.csv.gz
    published_phenotypes_file: nguyen_2020_inframe_mutant_phenotypes.csv.gz
    
wetmore:
    map_file: TnSeq_SB2B_ML5_l5.annotated.csv.gz
    counts_file: wetmore_2015_l5_mbarq_merged_counts.csv.gz
    results_file: Set1_rra_results.csv.gz
    sample_data_file: SB2B_metadata_carbon_source_set1.csv.gz
    published_counts_file: SB_count_table.poolcount.gz
    published_results_file: sb2b_ml5.gene_fitness.tab.gz
    published_stats_file: sb2b_t_stat.tab.gz
    
jasinska:
    sample_data_file: SraRunTable_Jasinska.txt
    no_drugs_file: 11-04-23_jasinska-no-drug_mbarq_merged_counts.csv.gz
    published_frequency_file: Jasinska_barcode_frequency.csv.gz
   
 