name:
    mbarq_manuscript
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - pyaml
  - scikit-learn
  - jupyter
  - python-kaleido
