name: mbarq_lite
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - mageck
  #- bioconductor-mageckflute
  #- r-base=4.1.3
  #- bioconductor-sva
  #- bioconductor-do.db=2.9=r41*
  #- bioconductor-go.db=3.14.0=r41*
  - python==3.8.*
  - blast==2.9.*
  - bedtools==2.30.*
  - biopython==1.79
  - numpy=1.22.1
  - pandas==1.3.3
  - pytest
  - click
  - pip
  - pandera
  - pretty_errors # optional and could be removed
  - pip
  - pip:
      - "--editable=git+https://github.com/MicrobiologyETHZ/mbarq#egg=mbarq"
