name: mbarq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - mageck
  - python==3.8.*
  - blast==2.9.*
  - bedtools==2.30.*
  - biopython==1.79
  - numpy=1.22.1
  - pandas==1.3.3
  - pytest
  - click
  - pip
  - pandera
  - pyranges==0.0.117
  - pybedtools == 0.9.0
  - pip
  - pip:
      - "--editable=git+https://github.com/MicrobiologyETHZ/mbarq#egg=mbarq"
