name: Python Package using conda environment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Add conda 
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: mbarq
        environment-file: mbarq_environment.yaml
        python-version: '3.10'
        auto-activate-base: false
    - name: test conda
      run: |
        conda info
        conda list
    - name: Install mbarq
      run: |
        pip install .
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
